### ISSUE TITLE
Mettre en place l'échange des fichiers tarifs via GitHub

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/Fournisseurs#1]
Paulhac, qui te fournit les fichiers ? Willy ? Alexiane ? Les fournisseurs direct ?
Mettre en place l'écghange via Github. On peut mettre des pièces jointes aux issues avec les tarifs. Ce sera plus clair que par mail et tu peux noter les temps dans tmetric.

**Comment by Paulhac** [comment]
Le fichier provient directement de GOLDA.
Il est MAJ automatiquement. (dernière MAJ le 2 octobre)

**Comment by MamboJoel** [comment]
Jean dit qu'il écrase le nom du distributeur que l'on souhaite vide. Il lui redonne manifestement une valeur. Comme "CAPVI".
Concernant le tarif nul : donc c'est logique, le tarif n'existe bien plus selon golda ?

**Comment by Paulhac** [comment]
Je viens de télécharger le fichier Tarif CAP VI depuis Golda.
Effectivement, cette pièce n'est PLUS dans le tarif.

**Comment by MamboJoel** [comment]
Alors c'est le comportement souhaité. Merci Paulhac.
Seul problème encore : on affiche toujours "CAPVI" alors qu'on voudrait le cacher.
Tx !

**Comment by jlenormant** [comment]
Est-ce que ça a du sens de garder cette référence dans la table recherche quand elle n'est plus dans le tarif ? pour catsdpv ça n'est pas gênant mais il faut que je prévoie en conséquence

**Comment by Paulhac** [comment]
aucun sens. car elle ne retourne aucune réf de la table Tarif.
Le mieux, serait que CAP VI nous donne un fichier des Ref OE à jour.

**Comment by MamboJoel** [comment]
Paulhac, tu t'es trompé d'issue quand tu m'as répondu la première fois.
Votre discussion sur recherche appartient à #2

Cette issue c'est pour que tu t'organises avec Willy et Alexiane pour gérer les tarifs via github.
